name: 'Cache Update'
description: 'Updates caches for Android builds'

inputs:
  optional_cache_key:
    description: 'Optional cache key'
    required: false
    default: ""
  arch:
    description: 'Architecture (arm64-v8a, x86_64)'
    required: false
    default: ""
  run_emulator_setup:
    description: 'Whether to run emulator setup steps'
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # JS Bundle and Assets Cache - Save only
    - name: Save JS Bundle and Assets Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: |
          android/app/src/main/assets/index.android.bundle
          android/app/src/main/res/drawable-*
          android/app/src/main/res/raw-*
        key: ${{ runner.os }}-js-bundle-${{ hashFiles('package.json', 'yarn.lock') }}-${{ hashFiles('src/**/*.{js,jsx,ts,tsx}', 'lib/**/*.{js,jsx,ts,tsx}', 'modules/**/*.{js,jsx,ts,tsx}', 'App.{js,jsx,ts,tsx}', 'index.{js,jsx,ts,tsx}') }}

    # Build Outputs Cache - Save only
    - name: Save Build Outputs Cache
      if: always() && inputs.arch != '' && inputs.optional_cache_key != 'integration-test' && inputs.optional_cache_key != 'unit-tests'
      uses: actions/cache/save@v4
      with:
        path: |
          android/app/build/intermediates
          android/app/build/tmp
          android/app/build/generated
          android/app/build/outputs
          android/app/build/intermediates/instrumented_classes
          android/app/build/intermediates/test_apk
          android/app/build/intermediates/test_apk_androidTest
        key: ${{ runner.os }}-build-outputs-${{ inputs.arch }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.sha }}

    # Gradle cache - Save only with architecture in key
    - name: Save Gradle Cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
          android/build-cache
        key: ${{ runner.os }}-gradle-${{ inputs.arch != '' && format('-{0}', inputs.arch) || '' }}${{ inputs.optional_cache_key != '' && format('-{0}', inputs.optional_cache_key) || '' }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        
    # Yarn cache - Save only
    - name: Save yarn cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: $(yarn config get cacheFolder)
        key: yarn-download-cache-${{ hashFiles('yarn.lock') }}

    # Yarn install state - Save only
    - name: Save yarn install state
      if: always()
      uses: actions/cache/save@v4
      with:
        path: .yarn/ci-cache/
        key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}

    # React Native cache - Save only
    - name: Save React Native cache
      if: always()
      uses: actions/cache/save@v4
      with:
        path: |
          node_modules/.cache/react-native
          node_modules/.cache/metro
          node_modules/.cache/@react-native-community/cli
        key: ${{ runner.os }}-react-native-${{ hashFiles('package.json', 'yarn.lock') }}

    # Android SDK and AVD cache - Save only
    - name: Save Android SDK and AVD Cache
      if: always() && inputs.run_emulator_setup == 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          ~/.android/*
        key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}