name: 'Common Setup'
description: 'Sets up Node.js, Yarn, JDK and Gradle for Android builds'

inputs:
  gradle_max_workers:
    description: 'Maximum number of Gradle workers'
    required: false
    default: "4"
  node_version:
    description: 'Node.js version to use'
    required: false
    default: "22.x"
  checkout_depth:
    description: 'Checkout depth for git'
    required: false
    default: "1"
  android_api_level:
    description: 'Android API level'
    required: false
    default: "34"
  android_build_tools_version:
    description: 'Android build tools version'
    required: false
    default: "34.0.0"
  arch:
    description: 'Architecture (arm64-v8a, x86_64)'
    required: false
    default: ""
  android_target:
    description: 'Android target'
    required: false
    default: "google_apis"
  android_profile:
    description: 'Android profile'
    required: false
    default: "7.6in Foldable"
  run_emulator_setup:
    description: 'Whether to run emulator setup steps'
    required: false
    default: "false"
  optional_cache_key:
    description: 'Optional cache key'
    required: false
    default: ""
  skip_codegen:
    description: 'Skip React Native codegen (for jobs that use pre-built APKs)'
    required: false
    default: "false"
  test_runner_only:
    description: 'Minimal setup for running pre-built APKs on emulator (skips Node, Yarn, Gradle, JS bundle)'
    required: false
    default: "false"
  skip_disk_space:
    description: 'Skip free disk space cleanup (for jobs that dont need extra space)'
    required: false
    default: "false"

outputs:
  build-outputs-cache-hit:
    description: 'Whether the build outputs cache was hit'
    value: ${{ steps.build-outputs-cache-restore.outputs.cache-hit }}
  android-cache-hit:
    description: 'Whether the Android SDK and AVD cache was hit'
    value: ${{ steps.android-cache.outputs.cache-hit }}
  yarn-cache-hit:
    description: 'Whether the yarn download cache was hit'
    value: ${{ steps.yarn-download-cache-restore.outputs.cache-hit }}
  yarn-install-state-cache-hit:
    description: 'Whether the yarn install state cache was hit'
    value: ${{ steps.yarn-install-state-cache-restore.outputs.cache-hit }}
  js-bundle-cache-hit:
    description: 'Whether the JS bundle cache was hit'
    value: ${{ steps.js-bundle-cache-restore.outputs.cache-hit }}
  gradle-deps-cache-hit:
    description: 'Whether the Gradle dependencies cache was hit'
    value: ${{ steps.gradle-deps-cache-restore.outputs.cache-hit }}
  gradle-cache-hit:
    description: 'Whether the Gradle cache was hit'
    value: ${{ steps.gradle-cache-restore.outputs.cache-hit }}
  react-native-cache-hit:
    description: 'Whether the React Native cache was hit'
    value: ${{ steps.react-native-cache-restore.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # Set CPU count for Gradle - use nproc to detect actual CPUs, fallback to input
    - name: Set CPU count
      run: |
        CPU_COUNT=$(nproc 2>/dev/null || echo "${{ inputs.gradle_max_workers }}")
        echo "MAX_WORKERS=${CPU_COUNT}" >> $GITHUB_ENV
        echo "GRADLE_MAX_WORKERS=${CPU_COUNT}" >> $GITHUB_ENV
        echo "Detected ${CPU_COUNT} CPUs for parallel builds"
      shell: bash

    # Free Disk Space - skip for test_runner_only or skip_disk_space
    # (emulator + APKs, or coverage merge jobs fit comfortably in default runner disk space)
    - name: Free Disk Space
      if: inputs.test_runner_only != 'true' && inputs.skip_disk_space != 'true'
      uses: endersonmenezes/free-disk-space@v3
      with:
        remove_android: false        # Keep Android SDK
        remove_dotnet: true          # Remove .NET (~3GB)
        remove_haskell: true         # Remove Haskell (~5GB)
        remove_tool_cache: false     # Keep tool cache
        remove_swap: false           # Keep swap
        remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox"
        remove_folders: "/usr/share/swift /usr/share/miniconda /usr/local/share/powershell"

    # Early cleanup of old Gradle caches BEFORE restoring (prevents accumulation)
    - name: Pre-cleanup old Gradle caches
      if: inputs.test_runner_only != 'true'
      shell: bash
      run: |
        echo "Pre-cleanup: Checking for old Gradle caches..."
        # Extract current Gradle version from wrapper properties
        CURRENT_GRADLE=$(grep distributionUrl android/gradle/wrapper/gradle-wrapper.properties | sed 's/.*gradle-\([0-9.]*\)-.*/\1/' || echo "")
        echo "Current Gradle version: ${CURRENT_GRADLE:-unknown}"
        
        # Aggressively clean old version caches
        if [[ -d ~/.gradle/caches ]]; then
          for dir in ~/.gradle/caches/8.*; do
            if [[ -d "$dir" && -n "$CURRENT_GRADLE" && "$dir" != *"$CURRENT_GRADLE"* ]]; then
              echo "Removing old cache: $dir"
              rm -rf "$dir"
            fi
          done
          # Always remove transforms cache - it's huge and regenerates
          rm -rf ~/.gradle/caches/transforms-* 2>/dev/null || true
        fi
        
        # Clean old wrapper distributions
        if [[ -d ~/.gradle/wrapper/dists ]]; then
          for dir in ~/.gradle/wrapper/dists/gradle-*; do
            if [[ -d "$dir" && -n "$CURRENT_GRADLE" && "$dir" != *"$CURRENT_GRADLE"* ]]; then
              echo "Removing old wrapper: $dir"
              rm -rf "$dir"
            fi
          done
        fi
        
        echo "Pre-cleanup complete. Disk space:"
        df -h / | tail -1

    - name: Use Node.js ${{ inputs.node_version }}
      if: inputs.test_runner_only != 'true'
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: "yarn"

    - name: Expose yarn config as "$GITHUB_OUTPUT"
      if: inputs.test_runner_only != 'true'
      id: yarn-config
      shell: bash
      run: |
        echo "CACHE_FOLDER=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

    # Yarn caches
    - name: Restore yarn cache
      if: inputs.test_runner_only != 'true'
      uses: actions/cache/restore@v4
      id: yarn-download-cache-restore
      with:
        path: ${{ steps.yarn-config.outputs.CACHE_FOLDER }}
        key: yarn-download-cache-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          yarn-download-cache-

    - name: Install dependencies
      if: inputs.test_runner_only != 'true'
      run: yarn install --immutable --inline-builds
      shell: bash
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false'
        YARN_NM_MODE: 'hardlinks-local'
        YARN_INSTALL_STATE_PATH: .yarn/ci-cache/install-state.gz
        HUSKY: '0'

    # Clean stale native build artifacts from node_modules
    # This prevents "duplicate class" errors when dependencies change
    # (e.g., react-native-worklets removed since reanimated includes it)
    - name: Clean stale node_modules build artifacts
      if: inputs.test_runner_only != 'true'
      shell: bash
      run: |
        echo "Cleaning stale native build artifacts from node_modules..."
        # Remove android build directories from all node_modules packages
        # These get recreated during build but can cause conflicts if cached
        find node_modules -path "*/android/build" -type d -prune 2>/dev/null | while read dir; do
          echo "Removing: $dir"
          rm -rf "$dir"
        done
        # Also clean any .transforms directories
        find node_modules -name ".transforms" -type d -prune 2>/dev/null | while read dir; do
          echo "Removing: $dir"
          rm -rf "$dir"
        done
        echo "Cleanup complete"

    - name: Restore yarn install state
      if: inputs.test_runner_only != 'true'
      id: yarn-install-state-cache-restore
      uses: actions/cache/restore@v4
      with:
        path: .yarn/ci-cache/
        key: ${{ runner.os }}-yarn-install-state-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: |
          ${{ runner.os }}-yarn-install-state-cache-

    # Cache JS Bundle and Assets
    - name: Restore JS Bundle and Assets Cache
      if: inputs.test_runner_only != 'true'
      uses: actions/cache/restore@v4
      id: js-bundle-cache-restore
      with:
        path: |
          android/app/src/main/assets/index.android.bundle
          android/app/src/main/res/drawable-*
          android/app/src/main/res/raw-*
        key: ${{ runner.os }}-js-bundle-${{ hashFiles('package.json', 'yarn.lock') }}-${{ hashFiles('src/**/*.{js,jsx,ts,tsx}', 'lib/**/*.{js,jsx,ts,tsx}', 'app/**/*.{js,jsx,ts,tsx}', 'modules/**/*.{js,jsx,ts,tsx}', 'App.{js,jsx,ts,tsx}', 'index.{js,jsx,ts,tsx}', 'global.css', 'tailwind.config.js') }}
        restore-keys: |
          ${{ runner.os }}-js-bundle-${{ hashFiles('package.json', 'yarn.lock') }}-
          ${{ runner.os }}-js-bundle-

    # Generate JS bundle if needed
    - name: Generate JS Bundle
      if: inputs.test_runner_only != 'true' && steps.js-bundle-cache-restore.outputs.cache-hit != 'true'
      run: yarn bundle:android --dev=true
      shell: bash

    # Note: JS Bundle is an exception - we need to save it immediately if generated
    # This is because it's used by subsequent steps and we can't wait until the end of the job

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Cache Gradle downloaded dependencies (separate from build cache for stability)
    # This uses a stable key so dependencies persist across gradle file changes
    # Prevents intermittent 403s from Maven Central rate limiting in CI
    - name: Restore Gradle Dependencies Cache
      if: inputs.test_runner_only != 'true'
      uses: actions/cache/restore@v4
      id: gradle-deps-cache-restore
      with:
        path: |
          ~/.gradle/caches/modules-2
          ~/.gradle/caches/jars-*
        key: ${{ runner.os }}-gradle-deps-v1-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-deps-v1-
          ${{ runner.os }}-gradle-deps-

    # Cache Gradle files
    # Note: Cache key includes gradle-wrapper.properties hash to invalidate on Gradle version changes
    - name: Restore Cache Gradle files
      if: inputs.test_runner_only != 'true'
      uses: actions/cache/restore@v4
      id: gradle-cache-restore
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          android/.gradle
          android/build-cache
        key: ${{ runner.os }}${{ inputs.optional_cache_key != '' && format('-{0}', inputs.optional_cache_key) || '' }}-gradle-${{ inputs.arch != '' && format('-{0}', inputs.arch) || '' }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        # Broad fallback patterns to share caches across jobs and branches
        # Falls back to: same job type -> any job type with same arch -> any cache with same arch
        restore-keys: |
          ${{ runner.os }}${{ inputs.optional_cache_key != '' && format('-{0}', inputs.optional_cache_key) || '' }}-gradle-${{ inputs.arch != '' && format('-{0}', inputs.arch) || '' }}-${{ hashFiles('**/gradle-wrapper.properties') }}-
          ${{ runner.os }}${{ inputs.optional_cache_key != '' && format('-{0}', inputs.optional_cache_key) || '' }}-gradle-${{ inputs.arch != '' && format('-{0}', inputs.arch) || '' }}-
          ${{ runner.os }}-gradle-${{ inputs.arch != '' && format('-{0}', inputs.arch) || '' }}-

    - name: Setup Gradle
      if: inputs.test_runner_only != 'true'
      uses: gradle/actions/setup-gradle@v4.0.0
      with:
        # Cache is writeable for: tag builds (to update after release) and manual dispatch from master (to refresh cache)
        # Cache is read-only for: PRs and manual dispatch from other branches
        cache-read-only: ${{ !(github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}
        cache-overwrite-existing: ${{ !(github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) }}
        gradle-home-cache-cleanup: true
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
          wrapper

    # Restore Build Outputs Cache if arch is provided
    # Unit tests can restore this to get pre-generated codegen artifacts from cache warmer
    - name: Restore Build Outputs Cache
      if: inputs.test_runner_only != 'true' && inputs.arch != '' && inputs.optional_cache_key != 'integration-test'
      uses: actions/cache/restore@v4
      id: build-outputs-cache-restore
      with:
        path: |
          android/app/build/intermediates
          android/app/build/tmp
          android/app/build/generated
          android/app/build/outputs
          android/app/build/intermediates/instrumented_classes
          android/app/build/intermediates/test_apk
          android/app/build/intermediates/test_apk_androidTest
        # Include yarn.lock to invalidate cache when JS deps change (affects codegen)
        key: ${{ runner.os }}-build-outputs-${{ inputs.arch }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'yarn.lock') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-outputs-${{ inputs.arch }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'yarn.lock') }}-
          ${{ runner.os }}-build-outputs-${{ inputs.arch }}-

    - name: Ccachify the Native Modules
      if: inputs.test_runner_only != 'true'
      shell: bash
      run: |
        chmod +x scripts/ccachify_native_modules.sh
        ./scripts/ccachify_native_modules.sh

    - name: Grant execute permission for gradlew
      if: inputs.test_runner_only != 'true'
      run: cd android && chmod +x gradlew
      shell: bash

    # Run codegen for all React Native libraries (required for New Architecture)
    # Skip for jobs that use pre-built APKs (integration test shards)
    - name: Generate React Native Codegen
      if: inputs.test_runner_only != 'true' && inputs.skip_codegen != 'true'
      run: |
        cd android && \
        ./gradlew generateCodegenSchemaFromJavaScript generateCodegenArtifactsFromSchema --parallel --max-workers=$MAX_WORKERS
      shell: bash

    # Cache React Native specific files
    - name: Restore Cache React Native files
      if: inputs.test_runner_only != 'true'
      uses: actions/cache/restore@v4
      id: react-native-cache-restore
      with:
        path: |
          node_modules/.cache/react-native
          node_modules/.cache/metro
          node_modules/.cache/@react-native-community/cli
        key: ${{ runner.os }}-react-native-${{ hashFiles('package.json', 'yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-react-native-

    # Android SDK and AVD cache for emulator tests
    - name: Restore Cache Android SDK and AVD
      if: inputs.run_emulator_setup == 'true'
      uses: actions/cache@v4
      id: android-cache
      with:
        path: |
          ~/.android/avd
          ~/.android/adb_usb.ini
          /usr/local/lib/android/sdk/system-images/android-${{ inputs.android_api_level }}
        key: ${{ runner.os }}-android-avd-${{ inputs.android_api_level }}-${{ inputs.android_target }}-${{ inputs.arch }}
        # Broader fallbacks to share AVD caches when target/arch might differ slightly
        restore-keys: |
          ${{ runner.os }}-android-avd-${{ inputs.android_api_level }}-${{ inputs.android_target }}-
          ${{ runner.os }}-android-avd-${{ inputs.android_api_level }}-

    # Setup Android SDK for emulator if needed and not cached
    - name: Setup Android SDK
      if: inputs.run_emulator_setup == 'true' && steps.android-cache.outputs.cache-hit != 'true'
      uses: android-actions/setup-android@v3
      with:
        packages: 'tools platform-tools system-images;android-${{ inputs.android_api_level }};${{ inputs.android_target }};${{ inputs.arch }}'
        accept-android-sdk-licenses: true
        log-accepted-android-sdk-licenses: false

    # Enable KVM for Emulator
    - name: Enable KVM for Emulator
      # Only run if run_emulator_setup is true BUT MUST HAPPEN REGARDLESS OF WHETHER CACHE IS HIT OR NOT.
      # Emulator needs these steps to be run every time
      if: inputs.run_emulator_setup == 'true'
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    # Create AVD and generate snapshot for caching
    - name: Create AVD and generate snapshot for caching
      if: inputs.run_emulator_setup == 'true' && steps.android-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.android_api_level }}
        target: ${{ inputs.android_target }}
        arch: ${{ inputs.arch }}
        profile: ${{ inputs.android_profile }}
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot
        disable-animations: true
        script: |
          adb wait-for-device
          adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          echo "Generated AVD snapshot for caching."

