name: 'Native Build'
description: 'Handles native build operations for Android'

inputs:
  arch:
    description: 'Architecture (arm64-v8a, x86_64)'
    required: true
  skip_native_build:
    description: 'Whether to skip native build steps'
    required: false
    default: "false"

outputs:
  native_build_hash:
    description: 'Hash of the external native tasks file'
    value: ${{ steps.native-build-hash.outputs.hash }}

runs:
  using: "composite"
  steps:
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ccache-${{ matrix.arch }}-${{ steps.native_hash.outputs.hash }}
        create-symlink: true

    # Check if ccache is installed and setup
    - name: Check ccache setup
      shell: bash
      run: |
        echo "Checking ccache setup"
        which ccache || echo "ccache not found in PATH"
        ccache -V
        ccache -p
        ccache -s

    - name: Ccachify the Native Modules
      shell: bash
      run: |
        chmod +x scripts/ccachify_native_modules.sh
        ./scripts/ccachify_native_modules.sh

    # Build native components if needed
    - name: Build Native Components
      id: build-native
      if: inputs.skip_native_build != 'true' && steps.check-op-sqlite-artifacts.outputs.cache-hit != 'true'
      env:
        CCACHE_DEBUG: 1
        CCACHE_VERBOSE: 1
      run: |
        echo "Building native components as op-sqlite artifacts were not available"
        cd android && \
        ./gradlew externalNativeBuildDebug \
                  externalNativeBuildRelease \
        --parallel --max-workers=4 --build-cache --configure-on-demand \
      shell: bash